# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 66aca420b363bf81091c471d47313d353104df7891b44faa5b43e62a1309f60b0b10673fd6de826dbb91a2b83e9f6c0807378ce2ecaa1f92d3da5068dd5f7af0

test:
  secret_key_base: a35d89d6dd0181c19a889551ca7c318235129dd88c5191fe62dee292f9e978dc4c8392ff1eea8b2a2c0857f42249866dde1834ed96e490717b19a7787b14e50a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
